Cleanup
Nekroze/cookiecutter-pypackage pull request #10
Opened 2020-01-23 16:16 UTC by Zeitsperre

2020-01-23 23:02 UTC, Nekroze requested changes

2020-01-23 23:02 UTC, Nekroze commented on cookiecutter.json
> +	"full_name": "Trevor James Smith",
These kinds of changes should remain in your fork, although that will not cause an issue to merge this in.

2020-01-23 23:02 UTC, Nekroze commented on README.rst
> +cookiecutter-pypackage-ouranos
I have not changed the name of the repo, this might be confusing.

2020-01-23 23:02 UTC, Nekroze commented on README.rst
> +Cookiecutter template (Ouranos recipe) for a Python package. See https://github.com/audreyr/cookiecutter.
This should probably be excluded from the merge to my repo, just to keep the delineation clear.

2020-01-23 23:02 UTC, Nekroze commented on {{cookiecutter.repo_name}}/CONTRIBUTING.rst
> +Report bugs at https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.repo_name }}/issues.
I see the reason for this but either this way or the old way we are excluding someone, can we instead make this `github_namespace` that cookiecutter asks for instead?

2020-01-23 23:02 UTC, Nekroze commented on LICENSE
> +Copyright (c) Audrey Roy Greenfeld and individual contributors.
Would this license require users of this template to provide a copy of this license text along with the dynamically generated one in order to be compliant?

2020-01-23 23:04 UTC, Nekroze commented
Hi @Zeitsperre 

Thank you for this contribution, there are some great improvements there that I and this repos users will like I think. Much appreciated. I have just left a few comments in places I have some questions or concerns before we merge this.

2020-01-24 16:07 UTC, Zeitsperre commented
Hi, please excuse the confusion!

I've been working off of a fork of yours for the organization I work with and was performing some changes to that fork. If you're interested in some of my changes though, I can re-fork this repo on my personal account certainly merge some of the more relevant ones towards yours and update yours accordingly.

2020-02-03 03:02 UTC, Nekroze commented
No worries @Zeitsperre, its great stuff and I would love to merge it. I am just concerned with the license and copyright changes/additions at present, I am not super comfortable merging this as is and then removing them or genericizing some stuff again. I will try to get some time this weekend to fork your branch and make those adjustments if that helps.

2020-08-26 19:17 UTC, Zeitsperre commented
Hi @Nekroze, I'm archiving this PR and moving the code under a personal account. I'll be able to generalize it a bit, making changes as needed there. Any interest in a fresher PR ?

2020-08-26 19:17 UTC, closed without merging

2020-09-08 00:27 UTC, Nekroze commented
apologies for the late reply, been moving house and this notification got lost along the way. If you have a more generic version @Zeitsperre that would be fantastic to PR, it is still on my todo list but its quite far down these days sadly.